# Generated by Django 5.2.14 on 2026-06-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='activityparticipant',
            table='activity_participant',
        ),
        migrations.AlterModelTable(
            name='classinfo',
            table='class_info',
        ),
        migrations.AlterModelTable(
            name='criterion',
            table='criterion',
        ),
        migrations.AlterModelTable(
            name='evaluation',
            table='evaluation',
        ),
        migrations.AlterModelTable(
            name='evaluationdetail',
            table='evaluation_detail',
        ),
        migrations.AlterModelTable(
            name='groupcriterion',
            table='group_criterion',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='subitem',
            table='sub_item',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
