# Generated by Django 5.2.14 on 2026-06-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0002_alter_user_options_alter_activity_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
