# Generated by Django 5.2.14 on 2026-06-23 02:31

import django.db.models.deletion
import drl_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0004_user_plain_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', drl_app.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='drl_app.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_organization',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
