# Generated by Django 5.2.14 on 2026-06-23 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0005_organization_alter_user_managers_userorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'class_position',
            },
        ),
        migrations.CreateModel(
            name='StudentClassPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_positions', to=settings.AUTH_USER_MODEL)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_positions', to='drl_app.classinfo')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='drl_app.classposition')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='drl_app.student')),
            ],
            options={
                'db_table': 'student_class_position',
                'unique_together': {('student', 'class_info', 'position')},
            },
        ),
    ]
