# Generated by Django 5.2.14 on 2026-06-23 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0006_classposition_studentclassposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration_minutes',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='activity',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=10.8501, max_digits=9),
        ),
        migrations.AddField(
            model_name='activity',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=106.7712, max_digits=9),
        ),
        migrations.AddField(
            model_name='activity',
            name='radius_meters',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='ActivityCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('selfie_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='drl_app.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='drl_app.student')),
            ],
            options={
                'db_table': 'activity_check_in',
            },
        ),
        migrations.CreateModel(
            name='ActivityCheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_time', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('selfie_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='drl_app.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='drl_app.student')),
            ],
            options={
                'db_table': 'activity_check_out',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('before_value', models.TextField(blank=True, null=True)),
                ('after_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'change_request',
            },
        ),
        migrations.CreateModel(
            name='FraudDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frauds', to='drl_app.activity')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frauds', to='drl_app.student')),
            ],
            options={
                'db_table': 'fraud_detection',
            },
        ),
        migrations.CreateModel(
            name='ActivityAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=0)),
                ('completion_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='drl_app.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='drl_app.student')),
            ],
            options={
                'db_table': 'activity_attendance',
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
