# Generated by Django 5.2.14 on 2026-06-25 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0008_activity_end_time_activity_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('organizer_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('participation_content', models.TextField(blank=True, null=True)),
                ('proposed_score', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('advisor_approved', 'Advisor Approved'), ('need_more_info', 'Need More Information'), ('rejected_by_advisor', 'Rejected By Advisor'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_activities', to='drl_app.student')),
            ],
            options={
                'db_table': 'external_activity',
            },
        ),
        migrations.CreateModel(
            name='EvidenceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_level', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='drl_app.externalactivity')),
            ],
            options={
                'db_table': 'evidence_review',
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('file_size', models.IntegerField()),
                ('file_url', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='drl_app.externalactivity')),
            ],
            options={
                'db_table': 'evidence_file',
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='drl_app.externalactivity')),
            ],
            options={
                'db_table': 'fraud_flag',
            },
        ),
    ]
