# Generated by Django 5.2.14 on 2026-06-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0009_externalactivity_evidencereview_evidencefile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcriterion',
            name='is_single_choice',
            field=models.BooleanField(default=False),
        ),
    ]
