# Generated by Django 5.2.14 on 2026-06-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0010_groupcriterion_is_single_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='allowed_classes',
            field=models.ManyToManyField(blank=True, related_name='activities', to='drl_app.classinfo'),
        ),
        migrations.AddField(
            model_name='activity',
            name='allowed_clubs',
            field=models.ManyToManyField(blank=True, related_name='activities', to='drl_app.organization'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_registration_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='scope_type',
            field=models.CharField(choices=[('all', 'Toàn trường'), ('class', 'Lớp'), ('club', 'CLB')], default='all', max_length=20),
        ),
    ]
