# Generated by Django 5.2.8 on 2026-07-01 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drl_app", "0012_criteria_sets"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("semester", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "source_file_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("summary_data", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcript_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transcript_import",
                "ordering": ("-uploaded_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="TranscriptImportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_code", models.CharField(max_length=50)),
                ("full_name", models.CharField(blank=True, default="", max_length=150)),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=4)),
                ("classification", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("MATCHED", "Matched"), ("NOT_FOUND", "Not Found")],
                        max_length=20,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcript_import_items",
                        to="drl_app.student",
                    ),
                ),
                (
                    "transcript_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="drl_app.transcriptimport",
                    ),
                ),
            ],
            options={
                "db_table": "transcript_import_item",
            },
        ),
    ]
