# Generated by Django 5.2.8 on 2026-07-01 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drl_app", "0013_transcriptimport_transcriptimportitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transcriptimport",
            old_name="source_file_name",
            new_name="original_filename",
        ),
        migrations.AddField(
            model_name="transcriptimport",
            name="class_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transcript_imports",
                to="drl_app.classinfo",
            ),
        ),
        migrations.AddField(
            model_name="transcriptimport",
            name="pdf_class_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="transcriptimport",
            name="preview_data",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="transcriptimport",
            name="school_year",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="transcriptimport",
            name="status",
            field=models.CharField(
                choices=[
                    ("VALIDATED", "Validated"),
                    ("IMPORTED", "Imported"),
                    ("FAILED", "Failed"),
                ],
                default="VALIDATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transcriptimportitem",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("MATCHED", "Matched"),
                    ("NOT_FOUND", "Not Found"),
                    ("CLASS_MISMATCH", "Class Mismatch"),
                    ("DUPLICATE", "Duplicate"),
                ],
                default="MATCHED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transcriptimportitem",
            name="remark",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="transcriptimport",
            name="class_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="transcriptimportitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("MATCHED", "Matched"),
                    ("NOT_FOUND", "Not Found"),
                    ("CLASS_MISMATCH", "Class Mismatch"),
                    ("DUPLICATE", "Duplicate"),
                ],
                max_length=20,
            ),
        ),
    ]
