# Generated by Django 5.2.14 on 2026-07-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0022_manual_evaluation_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_config',
            },
        ),
    ]
