# Generated by Django 5.2.14 on 2026-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0029_room_activity_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
