# Generated by Django 5.2.14 on 2026-07-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0030_activity_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
