# Generated by Django 5.2.14 on 2026-07-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0033_alter_evaluation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_soldier_card_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
