# Generated by Django 5.2.14 on 2026-07-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0034_activity_is_soldier_card_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptimportitem',
            name='absent_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
