# Generated by Django 5.2.14 on 2026-07-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0035_transcriptimportitem_absent_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.CharField(default='info', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='system', max_length=50),
        ),
    ]
