# Generated by Django 5.2.14 on 2026-07-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drl_app', '0036_notification_action_url_notification_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationdetail',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluationdetail',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
